#!/bin/bash
#SBATCH -p normal
#SBATCH --job-name=fastqc_cassava
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=24G
#SBATCH --output=%x_%j.out
#SBATCH --error=%x_%j.err

# Load the FastQC module
module load FastQC/0.11.9

# Define directories
RAW_DATA_DIR="/projects/large/CIBIG_cassava/FASTQ_DIR"
RESULTS_DIR="/home/liby/FASTQC_RESULTS"

# Run FastQC on the raw data files and output results directly to $RESULTS_DIR
fastqc "$RAW_DATA_DIR"/*.fq.gz -o "$RESULTS_DIR"
